version: "3.7"

services:

  nginx:
    image: nginx:1.19.5
    ports:
      - mode: host
        protocol: tcp
        target : 80
        published : 80
    networks:
      - myProject_network
    volumes:
      - /home/innamtt/nginx.conf:/etc/nginx/nginx.conf
      - my_project_static:/data/static/
      - my_project_media:/data/media/
      - my_project_log:/var/log/nginx/
    secrets:
      - NGINX_AUTH

  goaccess:
    image: allinurl/goaccess:1.5.1
    ports:
      - 7890:7890
    volumes:
      - my_project_log:/var/log/nginx/
    command: /var/log/nginx/myProject_access.log -o /var/log/nginx/report.html --real-time-html --log-format COMBINED

  django:
    image: my_project_django:5
    networks:
      - myProject_network
    volumes:
      - my_project_static:/home/my_project/staticfiles/
      - my_project_media:/home/my_project/media/
    secrets:
      - DJANGO_SECRET_KEY
      - MARIADB_USER
      - MARIADB_PASSWORD

  mariadb:
    image: mariadb:10.5
    networks:
      - myProject_network
    volumes:
      - myproject_mariadb:/var/lib/mysql
    secrets:
      - MARIADB_USER
      - MARIADB_ROOT_PASSWORD
      - MARIADB_PASSWORD
    environment:
      MARIADB_DATABASE: django
      MARIADB_USER_FILE: /run/secrets/MARIADB_USER
      MARIADB_PASSWORD_FILE: /run/secrets/MARIADB_PASSWORD
      MARIADB_ROOT_PASSWORD_FILE: /run/secrets/MARIADB_ROOT_PASSWORD


networks:
  myProject_network:

volumes:
  my_project_static:
  my_project_media:
  myproject_mariadb:
  my_project_log:

secrets:
  DJANGO_SECRET_KEY:
    external: true
  MARIADB_ROOT_PASSWORD:
    external: true
  MARIADB_USER:
    external: true
  MARIADB_PASSWORD:
    external: true
  NGINX_AUTH:
    external: true